"""empty message

Revision ID: 36a052d1711e
Revises: 8480b10ad53c
Create Date: 2024-11-28 20:57:08.702868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a052d1711e'
down_revision = '8480b10ad53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professionals', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
