"""empty message

Revision ID: f438e76cea44
Revises: 70b7c06e9fea
Create Date: 2024-12-03 01:54:54.623222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f438e76cea44'
down_revision = '70b7c06e9fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prof_busy_on_same_day', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_column('prof_busy_on_same_day')

    # ### end Alembic commands ###
